<?php

use Phinx\Migration\AbstractMigration;

class V18 extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call 'create()' or 'update()' and NOT 'save()' when working
     * with the Table class.
     */
    public function change()
    {
        $this->table('census')
            ->addColumn('name', 'string')
            ->addColumn('dni', 'string')
            ->addColumn('email', 'string')
            ->addColumn('phone', 'string')
            ->addColumn('council_id', 'integer')
            ->addIndex('dni', ['unique' => true])
            ->addIndex('email', ['unique' => true])
            ->addIndex('phone', ['unique' => true])
            ->create();

        $this->table('council')
            ->addColumn('name', 'string')
            ->addColumn('province', 'enum', ['values' => 'acoruna,lugo,ourense,pontevedra'])
            ->create();

        $concellos = [
            ['Mañón','acoruna'],
            ['Cariño','acoruna'],
            ['Ortigueira','acoruna'],
            ['Cedeira','acoruna'],
            ['Valdoviño','acoruna'],
            ['Cerdido','acoruna'],
            ['Moeche','acoruna'],
            ['San Sadurniño','acoruna'],
            ['Narón','acoruna'],
            ['Ferrol','acoruna'],
            ['Somozas (As)','acoruna'],
            ['Pontes de García Rodríguez (As)','acoruna'],
            ['Neda','acoruna'],
            ['Fene','acoruna'],
            ['Capela (A)','acoruna'],
            ['Mugardos','acoruna'],
            ['Ares','acoruna'],
            ['Cabanas','acoruna'],
            ['Pontedeume','acoruna'],
            ['Monfero','acoruna'],
            ['Oleiros','acoruna'],
            ['Miño','acoruna'],
            ['Coruña (A)','acoruna'],
            ['Malpica de Bergantiños','acoruna'],
            ['Sada','acoruna'],
            ['Vilarmaior','acoruna'],
            ['Arteixo','acoruna'],
            ['Bergondo','acoruna'],
            ['Paderne','acoruna'],
            ['Ponteceso','acoruna'],
            ['Laracha (A)','acoruna'],
            ['Culleredo','acoruna'],
            ['Carballo','acoruna'],
            ['Cambre','acoruna'],
            ['Irixoa','acoruna'],
            ['Betanzos','acoruna'],
            ['Abegondo','acoruna'],
            ['Coirós','acoruna'],
            ['Cabana de Bergantiños','acoruna'],
            ['Aranga','acoruna'],
            ['Laxe','acoruna'],
            ['Carral','acoruna'],
            ['Coristanco','acoruna'],
            ['Oza dos Ríos','acoruna'],
            ['Camariñas','acoruna'],
            ['Cerceda','acoruna'],
            ['Vimianzo','acoruna'],
            ['Zas','acoruna'],
            ['Cesuras','acoruna'],
            ['Curtis','acoruna'],
            ['Ordes','acoruna'],
            ['Muxía','acoruna'],
            ['Tordoia','acoruna'],
            ['Mesía','acoruna'],
            ['Santa Comba','acoruna'],
            ['Sobrado','acoruna'],
            ['Vilasantar','acoruna'],
            ['Val do Dubra','acoruna'],
            ['Dumbría','acoruna'],
            ['Frades','acoruna'],
            ['Trazo','acoruna'],
            ['Cee','acoruna'],
            ['Boimorto','acoruna'],
            ['Oroso','acoruna'],
            ['Mazaricos','acoruna'],
            ['Baña (A)','acoruna'],
            ['Fisterra','acoruna'],
            ['Pino (O)','acoruna'],
            ['Toques','acoruna'],
            ['Arzúa','acoruna'],
            ['Santiago de Compostela','acoruna'],
            ['Corcubión','acoruna'],
            ['Negreira','acoruna'],
            ['Melide','acoruna'],
            ['Ames','acoruna'],
            ['Carnota','acoruna'],
            ['Outes','acoruna'],
            ['Brión','acoruna'],
            ['Touro','acoruna'],
            ['Santiso','acoruna'],
            ['Muros','acoruna'],
            ['Boqueixón','acoruna'],
            ['Noia','acoruna'],
            ['Rois','acoruna'],
            ['Lousame','acoruna'],
            ['Teo','acoruna'],
            ['Vedra','acoruna'],
            ['Padrón','acoruna'],
            ['Porto do Son','acoruna'],
            ['Dodro','acoruna'],
            ['Rianxo','acoruna'],
            ['Boiro','acoruna'],
            ['Pobra do Caramiñal (A)','acoruna'],
            ['Ribeira','acoruna'],
            ['Vicedo (O)','lugo'],
            ['Xove','lugo'],
            ['Viveiro','lugo'],
            ['Cervo','lugo'],
            ['Burela','lugo'],
            ['Foz','lugo'],
            ['Ourol','lugo'],
            ['Valadouro (O)','lugo'],
            ['Muras','lugo'],
            ['Barreiros','lugo'],
            ['Alfoz','lugo'],
            ['Ribadeo','lugo'],
            ['Mondoñedo','lugo'],
            ['Lourenzá','lugo'],
            ['Trabada','lugo'],
            ['Abadín','lugo'],
            ['Xermade','lugo'],
            ['Vilalba','lugo'],
            ['Riotorto','lugo'],
            ['Pontenova (A)','lugo'],
            ['Pastoriza (A)','lugo'],
            ['Guitiriz','lugo'],
            ['Fonsagrada (A)','lugo'],
            ['Cospeito','lugo'],
            ['Castro de Rei','lugo'],
            ['Meira','lugo'],
            ['Ribeira de Piquín','lugo'],
            ['Begonte','lugo'],
            ['Pol','lugo'],
            ['Outeiro de Rei','lugo'],
            ['Negueira de Muñiz','lugo'],
            ['Friol','lugo'],
            ['Baleira','lugo'],
            ['Rábade','lugo'],
            ['Castroverde','lugo'],
            ['Lugo','lugo'],
            ['Navia de Suarna','lugo'],
            ['Corgo (O)','lugo'],
            ['Palas de Rei','lugo'],
            ['Guntín','lugo'],
            ['Baralla','lugo'],
            ['Becerreá','lugo'],
            ['Láncara','lugo'],
            ['Cervantes','lugo'],
            ['Monterroso','lugo'],
            ['Portomarín','lugo'],
            ['Páramo (O)','lugo'],
            ['Antas de Ulla','lugo'],
            ['Sarria','lugo'],
            ['Nogais (As)','lugo'],
            ['Paradela','lugo'],
            ['Triacastela','lugo'],
            ['Taboada','lugo'],
            ['Samos','lugo'],
            ['Saviñao (O)','lugo'],
            ['Pedrafita do Cebreiro','lugo'],
            ['Incio (O)','lugo'],
            ['Chantada','lugo'],
            ['Folgoso do Courel','lugo'],
            ['Bóveda','lugo'],
            ['Pobra do Brollón (A)','lugo'],
            ['Carballedo','lugo'],
            ['Monforte de Lemos','lugo'],
            ['Pantón','lugo'],
            ['Quiroga','lugo'],
            ['Sober','lugo'],
            ['Ribas de Sil','lugo'],
            ['Irixo (O)','ourense'],
            ['San Cristovo de Cea','ourense'],
            ['Piñor','ourense'],
            ['Beariz','ourense'],
            ['Boborás','ourense'],
            ['Carballiño (O)','ourense'],
            ['Vilamarín','ourense'],
            ['Peroxa (A)','ourense'],
            ['Rubiá','ourense'],
            ['Avión','ourense'],
            ['Vilamartín de Valdeorras','ourense'],
            ['Barco de Valdeorras (O)','ourense'],
            ['Maside','ourense'],
            ['Nogueira de Ramuín','ourense'],
            ['Coles','ourense'],
            ['Amoeiro','ourense'],
            ['Rúa (A)','ourense'],
            ['Leiro','ourense'],
            ['Castro Caldelas','ourense'],
            ['San Amaro','ourense'],
            ['San Xoán de Río','ourense'],
            ['Pereiro de Aguiar (O)','ourense'],
            ['Punxín','ourense'],
            ['Carballeda de Valdeorras','ourense'],
            ['Ourense','ourense'],
            ['Parada de Sil','ourense'],
            ['Carballeda de Avia','ourense'],
            ['Cenlle','ourense'],
            ['Teixeira (A)','ourense'],
            ['Pobra de Trives (A)','ourense'],
            ['Larouco','ourense'],
            ['Esgos','ourense'],
            ['Petín','ourense'],
            ['Beade','ourense'],
            ['Xunqueira de Espadanedo','ourense'],
            ['Barbadás','ourense'],
            ['Toén','ourense'],
            ['Ribadavia','ourense'],
            ['Montederramo','ourense'],
            ['Castrelo de Miño','ourense'],
            ['Melón','ourense'],
            ['Bolo (O)','ourense'],
            ['Veiga (A)','ourense'],
            ['Chandrexa de Queixa','ourense'],
            ['San Cibrao das Viñas','ourense'],
            ['Manzaneda','ourense'],
            ['Maceda','ourense'],
            ['Paderne de Allariz','ourense'],
            ['Arnoia (A)','ourense'],
            ['Cartelle','ourense'],
            ['Taboadela','ourense'],
            ['Merca (A)','ourense'],
            ['Allariz','ourense'],
            ['Baños de Molgas','ourense'],
            ['Cortegada','ourense'],
            ['Gomesende','ourense'],
            ['Xunqueira de Ambía','ourense'],
            ['Ramirás','ourense'],
            ['Celanova','ourense'],
            ['Viana do Bolo','ourense'],
            ['Vilar de Barrio','ourense'],
            ['Vilariño de Conso','ourense'],
            ['Pontedeva','ourense'],
            ['Laza','ourense'],
            ['Padrenda','ourense'],
            ['Bola (A)','ourense'],
            ['Quintela de Leirado','ourense'],
            ['Sandiás','ourense'],
            ['Rairiz de Veiga','ourense'],
            ['Verea','ourense'],
            ['Sarreaus','ourense'],
            ['Vilar de Santos','ourense'],
            ['Xinzo de Limia','ourense'],
            ['Castrelo do Val','ourense'],
            ['Bande','ourense'],
            ['Gudiña (A)','ourense'],
            ['Lobeira','ourense'],
            ['Cualedro','ourense'],
            ['Trasmiras','ourense'],
            ['Porqueira','ourense'],
            ['Mezquita (A)','ourense'],
            ['Entrimo','ourense'],
            ['Riós','ourense'],
            ['Blancos (Os)','ourense'],
            ['Lobios','ourense'],
            ['Muíños','ourense'],
            ['Monterrei','ourense'],
            ['Calvos de Randín','ourense'],
            ['Baltar','ourense'],
            ['Vilardevós','ourense'],
            ['Verín','ourense'],
            ['Oímbra','ourense'],
            ['Vila de Cruces','pontevedra'],
            ['Agolada','pontevedra'],
            ['Estrada (A)','pontevedra'],
            ['Silleda','pontevedra'],
            ['Lalín','pontevedra'],
            ['Pontecesures','pontevedra'],
            ['Valga','pontevedra'],
            ['Rodeiro','pontevedra'],
            ['Catoira','pontevedra'],
            ['Cuntis','pontevedra'],
            ['Caldas de Reis','pontevedra'],
            ['Forcarei','pontevedra'],
            ['Vilagarcía de Arousa','pontevedra'],
            ['Dozón','pontevedra'],
            ['Moraña','pontevedra'],
            ['Portas','pontevedra'],
            ['Vilanova de Arousa','pontevedra'],
            ['Illa de Arousa (A)','pontevedra'],
            ['Campo Lameiro','pontevedra'],
            ['Cerdedo','pontevedra'],
            ['Meis','pontevedra'],
            ['Barro','pontevedra'],
            ['Ribadumia','pontevedra'],
            ['Cambados','pontevedra'],
            ['Cotobade','pontevedra'],
            ['Grove (O)','pontevedra'],
            ['Pontevedra','pontevedra'],
            ['Meaño','pontevedra'],
            ['Poio','pontevedra'],
            ['Lama (A)','pontevedra'],
            ['Sanxenxo','pontevedra'],
            ['Ponte Caldelas','pontevedra'],
            ['Marín','pontevedra'],
            ['Bueu','pontevedra'],
            ['Vilaboa','pontevedra'],
            ['Soutomaior','pontevedra'],
            ['Fornelos de Montes','pontevedra'],
            ['Moaña','pontevedra'],
            ['Covelo','pontevedra'],
            ['Redondela','pontevedra'],
            ['Pazos de Borbén','pontevedra'],
            ['Cangas','pontevedra'],
            ['Mondariz','pontevedra'],
            ['Vigo','pontevedra'],
            ['Cañiza (A)','pontevedra'],
            ['Ponteareas','pontevedra'],
            ['Mos','pontevedra'],
            ['Crecente','pontevedra'],
            ['Mondariz-Balneario','pontevedra'],
            ['Porriño (O)','pontevedra'],
            ['Nigrán','pontevedra'],
            ['Salvaterra de Miño','pontevedra'],
            ['Gondomar','pontevedra'],
            ['Neves (As)','pontevedra'],
            ['Salceda de Caselas','pontevedra'],
            ['Arbo','pontevedra'],
            ['Baiona','pontevedra'],
            ['Oia','pontevedra'],
            ['Tui','pontevedra'],
            ['Tomiño','pontevedra'],
            ['Rosal (O)','pontevedra'],
            ['Guarda (A)','pontevedra'],
        ];

        foreach ($concellos as $concello) {
            $this->insert('council', [
                'name' => $concello[0],
                'province' => $concello[1],
            ]);
        }
    }
}
